local dap = require 'dap'
local widgets = require 'dap.ui.widgets'
vim.keymap.set('n', '<leader>dd', function()
  dap.continue()
  dap.repl.open()
  widgets.sidebar(widgets.scopes).open()
  widgets.sidebar(widgets.frames).open()
end)
vim.keymap.set('n', '<leader>dc', dap.continue)
vim.keymap.set('n', '<leader>dn', dap.step_over)
vim.keymap.set('n', '<leader>di', dap.step_into)
vim.keymap.set('n', '<leader>do', dap.step_out)
vim.keymap.set('n', '<leader>db', dap.toggle_breakpoint)
vim.keymap.set('n', '<leader>dl', dap.list_breakpoints)
vim.keymap.set('n', '<leader>dr', dap.repl.open)
vim.keymap.set('n', '<leader>dt', function()
  dap.terminate()
  dap.repl.close()
end)

-- vim.fn.sign_define('DapBreakpoint', { text = '■', texthl = '', linehl = '', numhl = '' })
-- vim.fn.sign_define('DapStopped', { text = '■', texthl = 'red', linehl = '', numhl = '' })

vim.keymap.set({ 'n', 'v' }, '<leader>dh', widgets.hover)
vim.keymap.set('n', '<Leader>df', function()
  widgets.centered_float(widgets.frames)
end)
vim.keymap.set('n', '<Leader>ds', function()
  widgets.centered_float(widgets.scopes)
end)
