vim.keymap.set("n", "<leader>gg", ":Git<cr>", { silent = true })
vim.keymap.set("n", "<leader>gc", ":Commits<cr>", { silent = true })
vim.keymap.set("n", "<leader>gb", ":Git blame<cr>", { silent = true })
vim.keymap.set("n", "<leader>gr", ":Gread<cr>", { silent = true })
vim.keymap.set("n", "<leader>gl", ":Git log<cr>", { silent = true })
